services:
  clanker-server:
    image: ${REGISTRY}/clanker:${RING}-${VERSION}
    restart: unless-stopped
    ports:
      - "${CLANKER_SERVER_HOST_IP}:${CLANKER_SERVER_HOST_PORT}:8000"
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - HOST_URL=http://${CLANKER_SERVER_HOST_IP}:${CLANKER_SERVER_HOST_PORT}
      - SMSGAP_URL=http://${SETTLER_IP}:${SMSGAP_PORT}
      - CONVERSATIONS_DB=/data/conversations.db
      - RING=${RING}
    volumes:
      - ./data:/data
